* rewrite tool. * add manpage. * add *.desktop menu. * add debian menu. * adapt debian/copyright

diff --git a/sidux-setpassword b/sidux-setpassword
--- a/sidux-setpassword
+++ b/sidux-setpassword
@@ -1,75 +1,177 @@
 #!/bin/sh
-# password dialog for Knoppix  Chris Liechti
-# based on sshstart by Klaus Knopper
-# apr 2003
-# (C) 2004-2006 Stefan Lippers-Hollmann <s.l-h@gmx.de> for Kanotix, GPL2
-
-PATH="/bin:/sbin:/usr/bin:/usr/sbin"
-export PATH
+# (C) 2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
+# GPL2
 
 # override tool behaviour through distro-defaults
 FLL_DISTRO_NAME="sidux"
 FLL_LIVE_USER="sidux"
-FLL_IMAGE_DIR="SIDUX"
-FLL_IMAGE_FILE="SIDUX"
-FLL_IMAGE_LOCATION="$FLL_IMAGE_DIR/$FLL_IMAGE_FILE"
-FLL_MOUNTPOINT="/SIDUX"
 
 [ -r /etc/default/distro ] && . /etc/default/distro
 
+bailout()
+{
+        ERROR_LEVEL="${1}"
+        REASON="${2}"
 
-if [ ! -d ${FLL_MOUNTPOINT}/etc ] ; then 
-	echo -e "FATAL ERROR!\nThis ${FLL_DISTRO_NAME} script must not be run on a regular system.\nAborting."
-	exit 1
-fi
+	printf "ERROR $ERROR_LEVEL:\t$REASON\n\n" >&2
 
-TITLE="Set password for user \"${FLL_LIVE_USER}\""
+	exit "$ERROR_LEVEL"
+}
 
-[ "`id -u`" != "0" ] && exec su-me "$0" "$@"
+print_copyright()
+{
+        cat \
+<<EOF
 
-XDIALOG_HIGH_DIALOG_COMPAT=1
-export XDIALOG_HIGH_DIALOG_COMPAT
+Copyright (C) 2007 F.U.L.L.S.T.O.R.Y Project
+Copyright (C) 2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
 
-DIALOG="dialog"
-[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"
+F.U.L.L.S.T.O.R.Y Project Homepage:
+http://developer.berlios.de/projects/fullstory
 
+F.U.L.L.S.T.O.R.Y Subversion Archive:
+svn://svn.berlios.de/fullstory/trunk
+http://svn.berlios.de/svnroot/repos/fullstory
+http://svn.berlios.de/viewcvs/fullstory (viewcvs)
+http://svn.berlios.de/wsvn/fullstory (websvn)
 
-# samba password file must be not be a link to the CD
-SMBPASS=/etc/samba/smbpasswd
-if [ -L $SMBPASS ] ; then
-	rm -f $SMBPASS
-	cp -a ${FLL_MOUNTPOINT}$SMBPASS $SMBPASS
-fi
+This program is free software; you can redistribute it and/or
+modify it under the terms of the GNU General Public License
+as published by the Free Software Foundation; version 2 of the
+License only.
 
-# localisation
-case "$LANG" in
-	de*) MESSAGE1="Passwort für Benutzer ${FLL_LIVE_USER}' setzen";
-	     MESSAGE2="Wiederhole Passwort";
-	     MESSAGE3="Passwörter stimmen nicht überein"; ;;
-	*)   MESSAGE1="Set password for user '${FLL_LIVE_USER}'";
-	     MESSAGE2="Retype password";
-	     MESSAGE3="Passwords did not match"; ;;
-esac
+This program is distributed in the hope that it will be useful,
+but WITHOUT ANY WARRANTY; without even the implied warranty of
+MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+GNU General Public License for more details.
 
-echo ""
+You should have received a copy of the GNU General Public License
+along with this package; if not, write to the Free Software
+Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
+MA 02110-1301, USA.
 
-FORCE=false
-echo "$@" | grep force && FORCE=true
+On Debian GNU/Linux systems, the text of the GPL license can be
+found in /usr/share/common-licenses/GPL-2.
 
-#loop while password is not set
-while grep -q '^${FLL_LIVE_USER}:\*:' /etc/shadow || grep -q '^${FLL_LIVE_USER}:$(getent passwd "$FLL_LIVE_USER" | cut -d\: -f2):XXXXX' /etc/samba/smbpasswd || $FORCE ; do
-	PASSWORD1=$($DIALOG --stdout --passwordbox "$MESSAGE1" 0 0) || break
-	PASSWORD2=$($DIALOG --stdout --passwordbox "$MESSAGE2" 0 0) || break
-	if [ "$PASSWORD1" = "$PASSWORD2" ] ; then
-		#set system password and samba password
-		echo "${FLL_LIVE_USER}:$PASSWORD1" | chpasswd
-		echo -e "$PASSWORD1\n$PASSWORD1" | smbpasswd -a ${FLL_LIVE_USER} -s
-	else
-		$DIALOG --msgbox "$MESSAGE3" 0 0
-	fi
-	#force is only executed once
-	FORCE=false
+EOF
+}
+
+print_help()
+{
+        cat \
+<<EOF
+
+Usage: $(basename $0) [options]
+  $(basename $0) is frontend to set user passwords, primarily targeted at 
+  live CD usages. Unless explicitly overriden with -u|--user, the password
+  dialogues for the executing user and root will be started.
+
+Options:
+  -C|--copyright	copyright information
+  -h|--help		information about using this program
+  -r|--no-root		don't change the root password.
+  -u|--user		specify username for setting a password
+  -v|--version		specify username for setting a password
+
+EOF
+}
+
+print_version()
+{
+	cat \
+<<EOF
+sidux-setpassword 0.2
+
+Copyright (C) 2007 F.U.L.L.S.T.O.R.Y Project
+Copyright (C) 2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
+
+This is free software; see "$0 --copyright" copying conditions.  There is NO
+warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+
+EOF
+}
+
+change_passwd()
+{
+	clear
+	printf "Change system password for \"${1}\":\n"
+
+	passwd "${1}" || bailout 4 "failed to set password for system account ${USERNAME}."
+}
+
+change_smbpasswd()
+{
+	clear
+	printf "Change/ add samba password for \"${1}\":\n"
+
+	smbpasswd -x "${1}"
+
+	smbpasswd -a "${1}" || bailout 5 "Failed to set samba password for ${USERNAME}."
+}
+
+ARGS=$(	getopt --name "$(basename $0)" \
+	--options Chru:v \
+	--long copyright,help,no-root,user:,version \
+	-- $@ )
+
+[ "$?" -ne 0 ] && bailout 1 "$(basename $0): getopt failed, terminating."
+
+eval set -- "$ARGS"
+
+NO_ROOT=""
+while [ "$#" -gt 1 ]; do
+	case $1 in
+		-C|--copyright)
+			print_copyright
+			exit 0
+			;;
+		-h|--help)
+			print_help
+			exit 0
+			;;
+		-r|--no-root)
+			NO_ROOT="yes"
+			;;
+		-u|--user)
+			shift
+			USERNAME="$1"
+			;;
+		-v|--version)
+			print_version
+			exit 0
+			;;
+		*)
+			printf "$(basename $0): invalid command line option\n" >&2
+			print_help
+			exit 2
+			;;
+	esac
+	shift
 done
 
-exit 0
+# determine username
+if [ -z "$USERNAME" ]; then
+	if [ "$(id -u)" -ne 0 ]; then
+		USERNAME="$(id -un)"
+	else
+		USERNAME="$FLL_LIVE_USER"
+	fi
+fi
+
+if ! getent passwd "$USERNAME" >/dev/null 2>&1; then
+	bailout 2 "\n$USERNAME is not a valid system account."
+fi
+
+# run me as root (only necessary if called as root in the first place)
+[ "$(id -u)" -ne 0 ] && exec su-me "$0" -u "$USERNAME"
+
+# change user password
+change_passwd "$USERNAME"
+
+# add samba user
+if [ -x /usr/bin/smbpasswd ] && pidof smbd >/dev/null 2>&1; then
+	change_smbpasswd "$USERNAME"
+fi
+
+[ ! "$NO_ROOT" = "yes" ] && change_passwd root
 
